import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import '../models/audit_event.dart';
import '../models/monitored_service.dart';
import 'database_service.dart';
import 'shizuku_service.dart';

class DiagnosticsReportService {
  final String displayLabel;
  final String serviceClass;
  final bool isMonitored;
  final bool isEnabled;
  final bool notificationsEnabled;
  final DateTime? lastRestarted;

  const DiagnosticsReportService({
    required this.displayLabel,
    required this.serviceClass,
    required this.isMonitored,
    required this.isEnabled,
    required this.notificationsEnabled,
    this.lastRestarted,
  });
}

class DiagnosticsService {
  static const _githubIssueUrl =
      'https://github.com/sklndev/Service-Keeper/issues/new';
  static const _prefillSoftLimit = 6500;

  final ShizukuService _shizuku;
  final DatabaseService _db;

  DiagnosticsService(this._shizuku, this._db);

  Future<String> buildServiceReport(
      MonitoredService service, String appName) async {
    final buf = StringBuffer();

    buf.writeln('## Service Issue Report');
    buf.writeln();
    buf.writeln('> Auto-generated by Service Keeper');
    buf.writeln();

    buf.writeln('### Service Details');
    buf.writeln('| Field | Value |');
    buf.writeln('|---|---|');
    buf.writeln('| App | $appName |');
    buf.writeln('| Package | `${service.packageName}` |');
    buf.writeln('| Service | ${service.displayLabel} |');
    buf.writeln('| Class | `${service.serviceClass}` |');
    final status = service.wasRunning == null
        ? 'Unknown'
        : (service.wasRunning! ? '✅ Running' : '❌ Not Running');
    buf.writeln('| Last Known Status | $status |');
    buf.writeln('| Check Interval | Every ${service.intervalMinutes}m |');
    buf.writeln(
        '| App Restart Enabled | ${service.appRestartEnabled ? 'Yes' : 'No'} |');
    buf.writeln('| Monitoring Enabled | ${service.enabled ? 'Yes' : 'No'} |');
    if (service.lastChecked != null) {
      buf.writeln('| Last Checked | ${service.lastChecked!.toIso8601String()} |');
    }
    if (service.lastRestarted != null) {
      buf.writeln(
          '| Last Restarted | ${service.lastRestarted!.toIso8601String()} |');
    }
    buf.writeln();

    await _appendDeviceInfo(buf);

    final events = await _db.getEvents(
      packageName: service.packageName,
      serviceClass: service.serviceClass,
      limit: 15,
    );
    _appendAuditEvents(buf, events, includeServiceCol: false);

    await _appendDumpsys(buf, service.packageName);

    return buf.toString();
  }

  Future<String> buildAppReport(
      String pkg, String appName, List<MonitoredService> services) async {
    final buf = StringBuffer();

    buf.writeln('## App Issue Report');
    buf.writeln();
    buf.writeln('> Auto-generated by Service Keeper');
    buf.writeln();

    buf.writeln('### App: $appName');
    buf.writeln('**Package:** `$pkg`  ');
    buf.writeln('**Services monitored:** ${services.length}');
    buf.writeln();

    buf.writeln('### Monitored Services');
    for (final s in services) {
      final dot = s.wasRunning == null
          ? '⚪'
          : (s.wasRunning! ? '🟢' : '🔴');
      buf.writeln('- $dot **${s.displayLabel}**');
      buf.writeln('  `${s.serviceClass}`');
      if (s.lastRestarted != null) {
        buf.writeln(
            '  Last restarted: ${s.lastRestarted!.toIso8601String()}');
      }
    }
    buf.writeln();

    await _appendDeviceInfo(buf);

    final events = await _db.getEvents(packageName: pkg, limit: 20);
    _appendAuditEvents(buf, events, includeServiceCol: true);

    await _appendDumpsys(buf, pkg);

    return buf.toString();
  }

  Future<String> buildExternalServiceReport({
    required String reportType,
    required String packageName,
    required String appName,
    required String serviceClass,
    required bool isMonitored,
    required bool isEnabled,
    required bool notificationsEnabled,
  }) async {
    final buf = StringBuffer();
    final label = serviceClass.split('.').last;

    buf.writeln('## $reportType Issue Report');
    buf.writeln();
    buf.writeln('> Auto-generated by Service Keeper');
    buf.writeln();

    buf.writeln('### Service Details');
    buf.writeln('| Field | Value |');
    buf.writeln('|---|---|');
    buf.writeln('| App | $appName |');
    buf.writeln('| Package | `$packageName` |');
    buf.writeln('| Service | $label |');
    buf.writeln('| Class | `$serviceClass` |');
    buf.writeln('| Monitoring Enabled | ${isMonitored ? 'Yes' : 'No'} |');
    buf.writeln('| Service State | ${isEnabled ? 'Enabled/Active' : 'Disabled/Inactive'} |');
    buf.writeln('| Notifications Enabled | ${notificationsEnabled ? 'Yes' : 'No'} |');
    buf.writeln();

    await _appendDeviceInfo(buf);

    final events = await _db.getEvents(
      packageName: packageName,
      serviceClass: serviceClass,
      limit: 20,
    );
    _appendAuditEvents(buf, events, includeServiceCol: false);

    await _appendDumpsys(buf, packageName);

    return buf.toString();
  }

  Future<String> buildExternalAppReport({
    required String reportType,
    required String packageName,
    required String appName,
    required List<DiagnosticsReportService> services,
  }) async {
    final buf = StringBuffer();

    buf.writeln('## $reportType App Issue Report');
    buf.writeln();
    buf.writeln('> Auto-generated by Service Keeper');
    buf.writeln();

    buf.writeln('### App: $appName');
    buf.writeln('**Package:** `$packageName`  ');
    buf.writeln('**Services monitored:** ${services.length}');
    buf.writeln();

    buf.writeln('### Services');
    for (final s in services) {
      final state = s.isEnabled ? 'Enabled/Active' : 'Disabled/Inactive';
      buf.writeln('- **${s.displayLabel}** (`${s.serviceClass}`)');
      buf.writeln('  - Monitored: ${s.isMonitored ? 'Yes' : 'No'}');
      buf.writeln('  - State: $state');
      buf.writeln('  - Notifications: ${s.notificationsEnabled ? 'Enabled' : 'Disabled'}');
      if (s.lastRestarted != null) {
        buf.writeln('  - Last restarted: ${s.lastRestarted!.toIso8601String()}');
      }
    }
    buf.writeln();

    await _appendDeviceInfo(buf);

    final events = await _db.getEvents(packageName: packageName, limit: 20);
    _appendAuditEvents(buf, events, includeServiceCol: true);

    await _appendDumpsys(buf, packageName);

    return buf.toString();
  }

  Future<void> _appendDeviceInfo(StringBuffer buf) async {
    try {
      final results = await Future.wait([
        _shizuku.exec('getprop ro.build.version.release'),
        _shizuku.exec('getprop ro.build.version.sdk'),
        _shizuku.exec('getprop ro.product.manufacturer'),
        _shizuku.exec('getprop ro.product.model'),
      ]);
      final android = results[0]?.trim() ?? '?';
      final api = results[1]?.trim() ?? '?';
      final mfr = results[2]?.trim() ?? '?';
      final model = results[3]?.trim() ?? '?';

      buf.writeln('### Device');
      buf.writeln('| Field | Value |');
      buf.writeln('|---|---|');
      buf.writeln('| Android | $android (API $api) |');
      buf.writeln('| Device | $mfr $model |');
      buf.writeln();
    } catch (_) {}
  }

  void _appendAuditEvents(StringBuffer buf, List<AuditEvent> events,
      {required bool includeServiceCol}) {
    if (events.isEmpty) return;
    buf.writeln('### Recent Events (${events.length})');
    if (includeServiceCol) {
      buf.writeln('| Time | Service | Event | Notes |');
      buf.writeln('|---|---|---|---|');
    } else {
      buf.writeln('| Time | Event | Notes |');
      buf.writeln('|---|---|---|');
    }
    for (final e in events) {
      final ts = e.timestamp.toIso8601String().substring(0, 19);
      final notes = (e.notes ?? '').replaceAll('|', '\\|');
      if (includeServiceCol) {
        buf.writeln('| $ts | ${e.displayLabel} | ${e.eventType.label} | $notes |');
      } else {
        buf.writeln('| $ts | ${e.eventType.label} | $notes |');
      }
    }
    buf.writeln();
  }

  Future<void> _appendDumpsys(StringBuffer buf, String packageName) async {
    try {
      final output =
          await _shizuku.exec('dumpsys activity services $packageName');
      if (output == null || output.trim().isEmpty) return;

      final lines = output.split('\n');
      final relevant = lines
          .where((l) =>
              l.contains('ServiceRecord') ||
              l.contains('Running services') ||
              l.contains('app=ProcessRecord'))
          .take(25)
          .join('\n');

      final snippet =
          relevant.isNotEmpty ? relevant : lines.take(20).join('\n');

      buf.writeln('### dumpsys activity services $packageName');
      buf.writeln('```');
      buf.writeln(snippet.trimRight());
      buf.writeln('```');
    } catch (_) {}
  }

  static Future<void> openGitHubIssue(
    BuildContext context, {
    required String title,
    required String body,
    bool preferAttachment = true,
    Uint8List? screenshotBytes,
  }) async {
    final payload = '**Title:** $title\n\n$body';
    final prefillEncodedLength = Uri.encodeQueryComponent(body).length;
    final tooLarge = prefillEncodedLength > _prefillSoftLimit;
    final attachment = await _writeAttachmentFile(title, body);

    final Uri uri;
    if (tooLarge) {
      await Clipboard.setData(ClipboardData(text: payload));
      final fallbackBody = [
        'Full diagnostics were too large for URL prefill and were copied to clipboard.',
        '',
        'Please paste the diagnostics below this line before submitting.',
        '',
        '---',
        '',
        _trimForFallback(body),
      ].join('\n');

      uri = Uri.parse(_githubIssueUrl).replace(
        queryParameters: {
          'title': title,
          'body': fallbackBody,
        },
      );
    } else {
      uri = Uri.parse(_githubIssueUrl).replace(
        queryParameters: {'title': title, 'body': body},
      );
    }

    final opened = await launchUrl(uri, mode: LaunchMode.externalApplication);
    if (!opened) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Could not open browser. Diagnostics were copied to clipboard.'),
          ),
        );
      }
      await Clipboard.setData(ClipboardData(text: payload));
      return;
    }

    if (preferAttachment && tooLarge && attachment != null) {
      await Share.shareXFiles(
        [XFile(attachment.path, mimeType: 'text/markdown')],
        subject: 'Service Keeper diagnostics attachment',
        text: 'Attach this diagnostics file to the GitHub issue.',
      );
    } else if (screenshotBytes != null) {
      await _shareScreenshot(screenshotBytes, title);
    }

    if (context.mounted) {
      final message = tooLarge
          ? 'Opened GitHub issue. Full diagnostics were copied to clipboard.'
          : 'Opened GitHub issue with diagnostics pre-filled.';
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(message)));
    }
  }

  static Future<void> _shareScreenshot(Uint8List bytes, String title) async {
    try {
      final now = DateTime.now();
      final ts =
          '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}_${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}';
      final safeTitle = title
          .toLowerCase()
          .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
          .replaceAll(RegExp(r'_+'), '_')
          .replaceAll(RegExp(r'^_|_$'), '');
      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/screenshot_${safeTitle}_$ts.png');
      await file.writeAsBytes(bytes);
      await Share.shareXFiles(
        [XFile(file.path, mimeType: 'image/png')],
        subject: 'Service Keeper screenshot',
        text: 'Attach this screenshot to the GitHub issue.',
      );
    } catch (_) {}
  }

  static String _trimForFallback(String body) {
    const maxChars = 1200;
    if (body.length <= maxChars) return body;
    return '${body.substring(0, maxChars)}\n\n...(truncated, full diagnostics copied to clipboard)';
  }

  static Future<File?> _writeAttachmentFile(String title, String body) async {
    try {
      final now = DateTime.now();
      final ts =
          '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}_${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}';
      final safeTitle = title
          .toLowerCase()
          .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
          .replaceAll(RegExp(r'_+'), '_')
          .replaceAll(RegExp(r'^_|_$'), '');
      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/diagnostics_${safeTitle}_$ts.md');
      await file.writeAsString('**Title:** $title\n\n$body');
      return file;
    } catch (_) {
      return null;
    }
  }
}
